# Franchise Application
spring.application.name=erp_franchise
server.port=8444

# HTTPS/SSL Configuration
            
#server.ssl.enabled=true
#server.ssl.key-store=/home/fuma/ssl-backend/backend.p12
#server.ssl.key-store-password=fuma@01234
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=backend

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.multi_tenant_connection_provider=com.franchise.Tenant.MultiTenantConnectionProvider
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.franchise.Tenant.TenantIdentifierResolver
spring.jpa.properties.hibernate.multiTenancy=SCHEMA

# Disable Spring's default datasource auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# File Upload Directory
file.upload-dir=D:/franchise/uploads/

# Static Resource Mapping
spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=file:D:/franchise/uploads/

